site_name: Owl of Athena
site_desc: 'The little owl of wisdom'

author: oxalorg

# Default values
# Can be removed from the config file
layout: post # can be overwritten on an individual basis
plugins_dir: _plugins
blog_dir: blog
